### ISSUE TITLE
doesn't build in arch linux

### ISSUE THREAD

**Issue by ghost** [spillerrec/imgviewer#55]
~/imgviewer-master  make                                                                          ✓  896 
Scanning dependencies of target imgviewer_autogen
[  4%] Automatic MOC, UIC and RCC for target imgviewer
Generating MOC source imgviewer_autogen/EWIEGA46WW/moc_fileManager.cpp
Generating MOC source imgviewer_autogen/EWIEGA46WW/moc_imageContainer.cpp
Generating MOC source imgviewer_autogen/EWIEGA46WW/moc_imageLoader.cpp
Generating MOC compilation imgviewer_autogen/moc_compilation.cpp
Generating UIC header imgviewer_autogen/include/ui_controls_ui.h
Generating RCC source imgviewer_autogen/3YJK5W5UP7/qrc_resources.cpp
[  4%] Built target imgviewer_autogen
Scanning dependencies of target qtimgviewer_autogen
[  8%] Automatic MOC and UIC for target qtimgviewer
Generating MOC source qtimgviewer_autogen/EWIEGA46WW/moc_imageCache.cpp
Generating MOC source qtimgviewer_autogen/EWIEGA46WW/moc_imageViewer.cpp
Generating MOC compilation qtimgviewer_autogen/moc_compilation.cpp
[  8%] Built target qtimgviewer_autogen
Scanning dependencies of target qtimgviewer
[ 12%] Building CXX object viewer/CMakeFiles/qtimgviewer.dir/colorManager.cpp.o
[ 16%] Building CXX object viewer/CMakeFiles/qtimgviewer.dir/imageCache.cpp.o
In file included from /home/arun/imgviewer-master/src/viewer/imageCache.h:22:0,
                 from /home/arun/imgviewer-master/src/viewer/imageCache.cpp:18:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::rotate180() const’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:37:45: error: could not convert ‘{((const Orientation*)this)->Orientation::rotation, (!(bool)((const Orientation*)this)->Orientation::flip_ver), (!(bool)((const Orientation*)this)->Orientation::flip_hor)}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
   { return { rotation, !flip_ver, !flip_hor }; }
                                             ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::rotateRight() const’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:39:53: error: could not convert ‘{((int8_t)(((int)((const Orientation*)this)->Orientation::rotation) + 1)), ((const Orientation*)this)->Orientation::flip_hor, ((const Orientation*)this)->Orientation::flip_ver}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
   { return { int8_t(rotation+1), flip_hor, flip_ver }; }
                                                     ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::mirror(bool, bool)’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:58:71: error: could not convert ‘{((Orientation*)this)->Orientation::rotation, (ver ? (!((Orientation*)this)->Orientation::flip_ver) : ((Orientation*)this)->Orientation::flip_ver), (hor ? (!((Orientation*)this)->Orientation::flip_hor) : ((Orientation*)this)->Orientation::flip_hor)}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
   { return { rotation, ver?!flip_ver:flip_ver, hor?!flip_hor:flip_hor }; }
                                                                       ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::normalized() const’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:63:49: error: could not convert ‘{((int8_t)(((int)rot) - 2)), (!(bool)((const Orientation*)this)->Orientation::flip_ver), (!(bool)((const Orientation*)this)->Orientation::flip_hor)}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
    return { int8_t(rot-2), !flip_ver, !flip_hor };
                                                 ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:65:37: error: could not convert ‘{rot, ((const Orientation*)this)->Orientation::flip_ver, ((const Orientation*)this)->Orientation::flip_hor}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
    return { rot, flip_ver, flip_hor };
                                     ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::add(Orientation) const’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:72:4: error: could not convert ‘{((int8_t)(((int)((const Orientation*)this)->Orientation::rotation) + ((int)other.Orientation::rotation))), (other.Orientation::flip_ver ? (!(bool)((const Orientation*)this)->Orientation::flip_ver) : ((bool)((const Orientation*)this)->Orientation::flip_ver)), (other.Orientation::flip_hor ? (!(bool)((const Orientation*)this)->Orientation::flip_hor) : ((bool)((const Orientation*)this)->Orientation::flip_hor))}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
    };
    ^
/home/arun/imgviewer-master/src/viewer/Orientation.hpp: In member function ‘Orientation Orientation::difference(Orientation) const’:
/home/arun/imgviewer-master/src/viewer/Orientation.hpp:82:4: error: could not convert ‘{((int8_t)(((int)b.Orientation::rotation) - ((int)a.Orientation::rotation))), (((int)a.Orientation::flip_ver) != ((int)b.Orientation::flip_ver)), (((int)a.Orientation::flip_hor) != ((int)b.Orientation::flip_hor))}’ from ‘<brace-enclosed initializer list>’ to ‘Orientation’
    };
    ^
make[2]: *** [viewer/CMakeFiles/qtimgviewer.dir/build.make:87: viewer/CMakeFiles/qtimgviewer.dir/imageCache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: viewer/CMakeFiles/qtimgviewer.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by spillerrec** [comment]
Tested on Arch, compiles fine now. Sorry for the delay, I currently do not have a working Arch setup, so I had to use the one I set up at work.

**Comment by arunsai123** [comment]
it works. thanks.
